project:
  type: website
  pre-render:
    - python scripts/fetch_github_repos.py
    - python scripts/update_gallery.py

website:
  title: 'iHuman Lab'
  favicon: images/logos/logo.png
  page-footer: |
    ![](/images/logos/logo_text.png){fig-align="center" width=65%}
  navbar:
    logo: images/logos/logo.png
    right:
      - icon: github
        href: https://github.com/iHuman-Lab
      - icon: youtube
        href: https://youtube.com/@ihuman-lab?si=DNK0QzRY-XgeOj5C
    left:
      - href: index.qmd
        text: Home
      - href: research
        text: Research
      - href: publications
        text: Publications
      - href: people
        text: People
      - href: news
        text: News
      - href: software
        text: Software
      - href: gallery
        text: Gallery
      - href: contact
        text: Join
      # - href: blogs
      #   text: Blogs

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    link-external-newwindow: true
